= UpperQuizz  API
Creado por Rodrigo Francisco <rhodfra@gmail.com>
Version 1.0, 26.06.2021
:toc: 
:toc-placement!:
:toclevels: 4                                          
:toc-title: Contenido
:imagesdir: ./README.assets/ 
:source-highlighter: pygments
ifndef::env-github[:icons: font]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

documentación de la API

== Endpoints

`**POST**` `upper-quizz.heroku.com/v1/login` ::
* _Request body_
+
|===
|Attribute | Type | Is required? 

|correo | String | required
|contrasena | String | required
|===
** Example
+
[source,json]
----
{
  "correo" : "rodrigo@gmail.com",
  "contrasena" : "diplomado123"
}
----
* Possible responses:
** _HTTP code_: `200`
+
[source,json]
----
{
  "message":"Usuario guardado correctamente"
}
----
** _HTTP code_: `400`
+ 
Algún dato fue incorrecto.

`*POST*` `upper-quizz.heroku.com/v1/register` ::
* _Request body_
+
|===
|Attribute | Type | Is required? 

|correo | String | required
|contrasena | String | required
|nombre | String | required
|apellidos | String | required
|===
** Example
+
[source,json]
----
{
  "correo" : "rodrigo@gmail.com",
  "contrasena" : "diplomado123",
  "nombre" : "Rodrigo",
  "apellidos" : "Francisco Pablo"
}
----
* Possible responses:
** _HTTP code_: `200`
+
[source,json]
----
{
  "message": "El usuario se registro correctamente"
}
----
** _HTTP code_: `400`
+
Fala algún dato para poder registrar al usuario
** _HTTP code_: `500`
+
Error del sistema para guardar al usuario


`*GET*` `upper-quizz.heroku.com/v1/evaluacion` ::
* *Login required*
* Obtiene todas las evaluaciones del usuario
* _NO body required_
* Possible responses:
** _HTTP code_: `200`
*** The responses has the following attributes
. evaluaciones *[array]*, cada elemento contiene:
.. evaluacion_id *[Int]*
.. examen_id *[Int]*
.. status *[String]*
.. aciertos_totales *[Int]*
.. num_intento *[Int]*
***  Example
+
[source,json]
----
{
  "evaluaciones": [
    {
      "evaluacion_id": 5,
      "examen_id": 1,
      "status": "NUNCA",
      "aciertos_totales": 0,
      "num_intento": 0
    },
    {
      "evaluacion_id": 6,
      "examen_id": 5,
      "status": "NUNCA",
      "aciertos_totales": 0,
      "num_intento": 0
    },
    {
      "evaluacion_id": 4,
      "examen_id": 7,
      "status": "NUNCA",
      "aciertos_totales": 0,
      "num_intento": 0
    }
  ]
}
----
** *NOTA* En caso de que no haya evaluaciones se regresa una array vacío

`*GET*` `upper-quizz.heroku.com/v1/evaluacion/:id` ::
* Obtiene los datos un examen, para pintar una por una las preguntas
* _NO body required_
* Possible responses:
** _HTTP code_: `200`
*** The responses has the following attributes
. evaluacion_id *[Int]*
. preguntas *[Array]*, cada elemento contiene:
.. texto_pregunta *[String]*
.. opcion_correcta_id *[Int]*
.. materia_id *[Int]*
.. pregunta_id *[Int]*
.. opciones *[Array]*, cada elemento contiene:
... opcion_id *[Int]*
... texto_opcion *[String]*
***  Example
+
[source,json]
----
{
  "evaluacion": [
    {
      "materia_id": 1,
        "opcion_correcta_id": 1,
        "opciones": [
          {
            "opcion_id": 1,
            "texto_opcion": "Especially value use."
          },
          {
            "opcion_id": 2,
            "texto_opcion": "Very garden memory rise."
          },
          {
            "opcion_id": 3,
            "texto_opcion": "Special they almost down quickly article."
          },
          {
            "opcion_id": 4,
            "texto_opcion": "Environmental various still success training."
          }
        ],
        "pregunta_id": 1,
        "texto_pregunta": "Card station seem relate sister fall."
    },
    {
      "materia_id": 1,
      "opcion_correcta_id": 8,
      "opciones": [
        {
          "opcion_id": 5,
          "texto_opcion": "Middle job skill success no establish."
        },
        {
          "opcion_id": 6,
          "texto_opcion": "Artist ball by decide activity above."
        },
        {
          "opcion_id": 7,
          "texto_opcion": "Indeed population everything couple whatever research."
        },
        {
          "opcion_id": 8,
          "texto_opcion": "Hotel star current democratic."
        }
      ],
      "pregunta_id": 2,
      "texto_pregunta": "Out audience the away law. Crime may boy agree."
    }
  ]
}
----
** _HTTP code_: `400`
+
[source,json]
----
{
  "message": "No se encontró la evaluación solicitada"
}
----


`*GET*` `upper-quizz.heroku.com/v1/historial` ::
* *Login required*
* Devuelve los puntajes de todas las evaluaciones terminadas

* _NO body required_
* Possible responses:
** _HTTP code_: `200`
*** The responses has the following attributes
. historial *[Array]*, cada elemento contiene:
.. aciertos_totales *[Int]*
.. evaluacion_id *[Int]*
.. fecha_aplicacion *[Date]*
.. nombre_examen *[String]*
***  Example
+
[source,json]
----
{
    "historial": [
        {
            "aciertos_totales": 60,
            "evaluacion_id": 5,
            "fecha_aplicacion": "Thu, 06 May 2021 15:03:03 GMT",
            "nombre_examen": "Simulación UNAM 2012"
        }
    ]
}
----
** *NOTA* En caso de que no haya evaluaciones se regresa una objeto vacío

`*GET*` `upper-quizz.heroku.com/v1/historial/:id` ::
* *Login required*
* Obtiene los puntajes de cada materia 
* _NO body required_
* Possible responses:
** _HTTP code_: `200`
*** The responses has the following attributes
. historial *[Obj]*
.. aciertos_totales *[Int]*
.. evaluacion_id *[Int]*
.. num_intento *[Int]*
.. puntaje_materia *[Array]*, cada elemento es un objeto que contiene
... materia_id *[Int]*
... nombre_materia *[String]*
... puntaje *[Int]*
***  Example
+
[source,json]
----
{
    "historial": {
        "aciertos_totales": 60,
        "evaluacion_id": "5",
        "num_intento": 1,
        "puntaje_materia": [
            {
                "materia_id": 1,
                "nombre_materia": "Matemáticas",
                "puntaje": 10
            },
            {
                "materia_id": 2,
                "nombre_materia": "Español",
                "puntaje": 8
            },
            {
                "materia_id": 3,
                "nombre_materia": "Física",
                "puntaje": 5
            },
            {
                "materia_id": 4,
                "nombre_materia": "Química",
                "puntaje": 3
            },
            {
                "materia_id": 5,
                "nombre_materia": "Biología",
                "puntaje": 1
            },
            {
                "materia_id": 6,
                "nombre_materia": "Historia Universal",
                "puntaje": 6
            },
            {
                "materia_id": 7,
                "nombre_materia": "Historia de México",
                "puntaje": 0
            },
            {
                "materia_id": 8,
                "nombre_materia": "Literatura",
                "puntaje": 4
            },
            {
                "materia_id": 9,
                "nombre_materia": "Geografía",
                "puntaje": 1
            },
            {
                "materia_id": 10,
                "nombre_materia": "Filosofía",
                "puntaje": 8
            }
        ]
    }
}
----
** _HTTP code_: `400`
+
[source,json]
----
{
  "message":"No existe la evaluación solicitada"
}
----

`*POST*` `upper-quizz.heroku.com/v1/evaluacion/:id/pregunta/:pregunta-id` ::
* *Login required*
* Registra la opción seleccionada en un pregunta dada una evaluación
* _Request body_
+
|===
|Attribute | Type | Is required? 

|opcion_seleccionada | Int | required
|===
** Example
+
[source,json]
----
{
  "opcion_seleccionada": 1,
}
----
* Possible responses:
** _HTTP code_: `200`
+
[source,json]
----
{
  "message": "Opción guardada exitosamente"
}
----
** _HTTP code_: `400`
+
[source,json]
----
{
  "message": "El usuario no mando la opción correcta"
}
----
** _HTTP code_: `500`
+
[source,json]
----
{
  "message": "El sistema tuvo problemas para guardar la respuesta"
}
----


`*POST*` `upper-quizz.heroku.com/v1/evaluacion/:id/calificar` ::
* *Login required*
* Registra el puntaje obtenido por cada una de las materias del examen y el
puntaje general.
* _Request body_
+
|===
|Attribute | Type | Is required? 

|evaluacion_id | Int | required
|fecha_aplicacion | String | required
|puntaje_materia | Array | required
|===
+
_Puntaje materia_ attributes:
+
|===
|Attribute | Type | Is required? 

|materia_id | Int | required
|puntaje | Int | required
|===
+
** Example
+
[source,json]
----
{
    "aciertos_totales": 60,
    "fecha_aplicacion": "2021-05-06 15:03:03",
    "puntaje_materia": [
        {
            "materia_id": 1,
            "puntaje": 10
        },
                {
            "materia_id": 2,
            "puntaje": 8
        },
                {
            "materia_id": 3,
            "puntaje": 5
        },
                {
            "materia_id": 4,
            "puntaje": 3
        },
                {
            "materia_id": 5,
            "puntaje": 1
        },
                {
            "materia_id": 6,
            "puntaje": 6
        },
                {
            "materia_id": 7,
            "puntaje": 0
        },
                {
            "materia_id": 8,
            "puntaje": 4
        },
                {
            "materia_id": 9,
            "puntaje": 1
        },
                {
            "materia_id": 10,
            "puntaje": 8
        }
    ]
}
----
* Possible responses:
** _HTTP code_: `200`
+
[source,json]
----
{
  "message": "Evaluación guardada correctamente"
}
----
** _HTTP code_: `400`
+
Mensajes de error en caso de que no se proporcionen adeacuadamente los datos
** _HTTP code_; `500`
+
[source,json]
----
{
  "message": "El sistema tuvo problemas para guardar las calificaciones"
}
----
